owner: nurzhanmarket
repo: upptime

sites:
  - name: Main Page
    url: $MAIN_PAGE
  - name: Product Page (Apple iPhone 15 Pro 128gb Natural Titanium)
    url: $PRODUCT_PAGE
  - name: 3rd level Category Page (Smartphones)
    url: $CATEGORY_PAGE
  - name: Admin Page
    url: $ADMIN_PAGE
  - name: test google 404
    url: https://www.google.com/

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status pages
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
